baseURL: https://richard-cokecola.github.io/
languageCode: en-us
title: Richard's Lullaby
theme: mini

# for exampleSite only, you may need to delete the line: `themesDir: ../../` 
# themesDir: ../../

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

googleAnalytics: G-HQLWYE4FVQ
# disqusShortname: your-disqus-shortname

# Hugo Configure Markup
# see: https://gohugo.io/getting-started/configuration-markup#highlight
markup:
  highlight:
    guessSyntax: true
    style: emacs


# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  # e.g.
  github: https://github.com/Richard-CokeCola/
  # heart: richardwei@protonmail.com
  #twitter: your-github-link
  #stackoverflow: your-github-link
  # facebook: your-facebook-link


# Site parameters
params:
  # Site Author
  author: Richard
  # Author biography
  bio: 
  # Site Description, used in HTML meat
  description: Richard's Lullaby
  #enableRSS: true
  
  # To enable comments, you may need to set `disqusShortname`
  #enableComments: true
  # To enable googleAnalytics, you may need to set `googleAnalytics`
  enableGoogleAnalytics: true


  # Optional
  home: '' # Default: Home
  about: '' # Default: About
  archive: '' # Default: Archive
  tags: '' # Default: Tags
  subscribe: '' # Default: Subscribe
  olderPosts: 'Older Posts' # Default: Older Posts
  newerPosts: 'Newer Posts' # Default: Newer Posts
  copyright: 'An engineer who is interested in AI, music, cooking, and some other things. You can contact me via email: richardwei@protonmail.com' # Default: © Copyright 2021 ❤️ author
  title404: '404 - You are at the middle of nowhere' # Default: 404 - Page Not Found
  subtitle404: 'You are at the middle of nowhere' # Default: The content you're looking for doesn't seem to exist.
  readMore: '' # Default: Read More

  # Extra links in navigation
  links:
    # e.g.
    # - name: Project
    #   path: /project
